#!/usr/bin/env bash
# This script configures /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

sudo grep -v -E 'localhost|facebook.com' /etc/hosts > /tmp/hosts
sudo cat /tmp/hosts > /etc/hosts
sudo echo "127.0.0.2 localhost" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts
